global:
    scrape_interval: 10s
    scrape_timeout: 10s
    evaluation_interval: 10s

alerting:
    alertmanagers:
        - static_configs:
            - targets:
                - alertmanager:9093

rule_files:
    - prometheus.rules.yml

scrape_configs:
    # Using Blackbox exporter
    - job_name: Application URL
      metrics_path: /probe
      params:
          module: [http_2xx]
      static_configs:
          - targets:
              - http://load-balancer/actuator/health
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115

    # Using Actuator exporter
    - job_name: Application Metrics
      metrics_path: /actuator/prometheus
      static_configs:
          - targets:
              - instance1:8080
              - instance2:8080

    # Using MySQL exporter
    - job_name: Database Metrics
      metrics_path: /metrics
      static_configs:
          - targets:
              - mysql-exporter:9104
            labels:
                db_host: 'db:3306'
                db_name: 'service_db'
