{
 "title": "Application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Max command request time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (instance, command) (rate(app_command_timer_seconds_max[1m]))",
     "legendFormat": "{{instance}} - {{command}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(app_tasks_background_count) by (job)",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Requests/minute",
   "type": "stat",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[1m])\n)",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  }
 ]
}