apiVersion: 1

deleteDatasources:
    - name: Prometheus
      orgId: 1
    - name: MySQL
      orgId: 2

datasources:
    - name: Prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      version: 1
      isDefault: true
      editable: false
